Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    raise NameError("¡Nombre no válido!")
NameError: ¡Nombre no válido!