False
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
    pizza.pinia_permitida = True
AttributeError: can't set attribute